exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "backup"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
  
# Site settings
title: Danish Society for Artificial Intelligence
title_alt : Dansk Selskab for Kunstig Intelligens
url: "https://dsai.sdu.dk" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

navigation_header:
  Home: /
  Join the Community: /join
  Members: /members
  Board: /board
  Statutes: /statutes

navigation_header_alt:
  Forside: /dk.html
  Deltag i Selskab: /join/dk.html
  Medlemmer: /members/dk.html
  Bestyrelse: /board/dk.html
  Statutes: /statutes/dk.html
