exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "backup"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
  
# Site settings
title: Danish Society for Artificial Intelligence
url: "https://mauro1.sdu.dk" # the base hostname & protocol for your site
baseurl: "/dsai"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

navigation_header:
  Home: /
  Join the Community: /join
  Members: /members
  Board: /board

navigation_header_alt:
  Forside: /dk
  Deltag i Samfundet: /join/dk
  Medlemmer: /members/dk
  Bestyrelse: /board/dk
